/*
 * This source file was generated by the Gradle 'init' task
 */
package moe.lita.antikythera;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void loadContext() {
        new App();
    }
}
